/* eslint-disable prettier/prettier */
export const columns = [
  { name: 'NAME', uid: 'name' },
  { name: 'ROLE', uid: 'role' },
  { name: 'STATUS', uid: 'status' },
  { name: 'ACTIONS', uid: 'actions' },
];

export const users = [
  {
    id: 1,
    name: 'Trần Văn Quyết',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Trần Thị Thùy Duyên',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'rời',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Nguyễn Thị Thanh Giang',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'Bạch Nam Sơn',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'nghỉ phép',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Nguyễn Thị Minh',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Đinh Hoàng Lộc',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 10,
    name: 'Trần Thị Thùy Duyên',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 8,
    name: 'Nguyễn Thị Bảo Trân',
    role: 'Cán bộ/Công nhân viên',
    team: '',
    status: 'trực tuyến',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 7,
    name: 'Zoey Lang',
    role: 'Technical Lead',
    team: 'Development',
    status: 'rời',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },

  {
    id: 9,
    name: 'William Howard',
    role: 'Community Manager',
    team: 'Marketing',
    status: 'nghỉ phép',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
  },
  {
    id: 11,
    name: 'Tony Reichert',
    role: 'CEO',
    team: 'Management',
    status: 'trực tuyến',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 12,
    name: 'Kristen Copper',
    role: 'Sales Manager',
    team: 'Sales',
    status: 'trực tuyến',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 13,
    name: 'Jane Fisher',
    role: 'Senior Developer',
    team: 'Development',
    status: 'trực tuyến',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 14,
    name: 'Zoey Lang',
    role: 'Technical Lead',
    team: 'Development',
    status: 'rời',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },
  {
    id: 15,
    name: 'Tony Reichert',
    role: 'CEO',
    team: 'Management',
    status: 'trực tuyến',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 16,
    name: 'Kristen Copper',
    role: 'Sales Manager',
    team: 'Sales',
    status: 'trực tuyến',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
];
